export const GET_INGRID_REQUEST: 'GET_INGRID_REQUEST' = 'GET_INGRID_REQUEST';
export const GET_INGRID_SUCCESS: 'GET_INGRID_SUCCESS' = 'GET_INGRID_SUCCESS';
export const GET_INGRID_FAILED: 'GET_INGRID_FAILED' = 'GET_INGRID_FAILED';
export const ADD_INGRID: 'ADD_INGRID' = 'ADD_INGRID';
export const ADD_INGRIDS: 'ADD_INGRIDS' = 'ADD_INGRIDS';
export const POST_ORDER_NUMBER_REQUEST: 'POST_ORDER_NUMBER_REQUEST' = 'POST_ORDER_NUMBER_REQUEST';
export const POST_ORDER_NUMBER_SUCCESS: 'POST_ORDER_NUMBER_SUCCESS' = 'POST_ORDER_NUMBER_SUCCESS';
export const POST_ORDER_NUMBER_FAILED: 'POST_ORDER_NUMBER_FAILED' = 'POST_ORDER_NUMBER_FAILED';
export const DELETE_INGRIDIENT: 'DELETE_INGRIDIENT' = 'DELETE_INGRIDIENT';
export const CHANGE_CARTS: "CHANGE_CARTS" = "CHANGE_CARTS";

export const INCREMENT: 'INCREMENT' = "INCREMENT";
export const DECREMENT: 'DECREMENT' = "DECREMENT";
export const RESET: 'RESET' = "RESET";

export const REGISTER_SUCCESS: "REGISTER_SUCCESS" = 'REGISTER_SUCCESS';
export const REGISTER_FAILED: "REGISTER_FAILED" = 'REGISTER_FAILED';
export const REGISTER_REQUEST: "REGISTER_REQUEST" = 'REGISTER_REQUEST';

export const GET_USER_REQUEST: "GET_USER_REQUEST" = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS: "GET_USER_SUCCESS" = 'GET_USER_SUCCESS';
export const GET_USER__FAILED: "GET_USER__FAILED" = 'GET_USER__FAILED';

export const SET_AUTH_CHECKED: "SET_AUTH_CHECKED" = 'SET_AUTH_CHECKED';

export const LOGOUT_SUCCESS: "LOGOUT_SUCCESS" = 'LOGOUT_SUCCESS';

export const SET_USER: "SET_USER" = 'SET_USER';

export const LOGIN_SUCCESS: "LOGIN_SUCCESS" = 'LOGIN_SUCCESS';
export const LOGIN_REQUEST: "LOGIN_REQUEST" = 'LOGIN_REQUEST';
export const LOGIN_FAILED: "LOGIN_FAILED" = 'LOGIN_FAILED';

export const UPDATE_USER_INFO_SUCCESS: "UPDATE_USER_INFO_SUCCESS" = 'UPDATE_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_FAILED: "UPDATE_USER_INFO_FAILED" = 'UPDATE_USER_INFO_FAILED';
export const UPDATE_USER_INFO_REQUEST: "UPDATE_USER_INFO_REQUEST" = 'UPDATE_USER_INFO_REQUEST';

export const FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST" = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS" = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED: "FORGOT_PASSWORD_FAILED" = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST" = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS: "RESET_PASSWORD_SUCCESS" = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED: "RESET_PASSWORD_FAILED" = 'RESET_PASSWORD_FAILED';