export const GET_INGRID_REQUEST: 'GET_INGRID_REQUEST' = 'GET_INGRID_REQUEST';
export const GET_INGRID_SUCCESS: 'GET_INGRID_SUCCESS' = 'GET_INGRID_SUCCESS';
export const GET_INGRID_FAILED: 'GET_INGRID_FAILED' = 'GET_INGRID_FAILED';
export const ADD_INGRID: 'ADD_INGRID' = 'ADD_INGRID';
export const ADD_INGRIDS: 'ADD_INGRIDS' = 'ADD_INGRIDS';
export const POST_ORDER_NUMBER_REQUEST: 'POST_ORDER_NUMBER_REQUEST' = 'POST_ORDER_NUMBER_REQUEST';
export const POST_ORDER_NUMBER_SUCCESS: 'POST_ORDER_NUMBER_SUCCESS' = 'POST_ORDER_NUMBER_SUCCESS';
export const POST_ORDER_NUMBER_FAILED: 'POST_ORDER_NUMBER_FAILED' = 'POST_ORDER_NUMBER_FAILED';
export const DELETE_INGRIDIENT: 'DELETE_INGRIDIENT' = 'DELETE_INGRIDIENT';
export const CHANGE_CARTS: "CHANGE_CARTS" = "CHANGE_CARTS";
export const CURRENT_INGRID: "CURRENT_INGRID" = "CURRENT_INGRID"

export const INCREMENT: 'INCREMENT' = "INCREMENT";
export const DECREMENT: 'DECREMENT' = "DECREMENT";
export const RESET: 'RESET' = "RESET";